# Generated by Django 3.2.5 on 2021-07-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_auto_20210709_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usersapp.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usersapp.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='room',
            field=models.CharField(blank=True, max_length=10, verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usersapp.street', verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersapp.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Наименование на английском'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='corpuser',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersapp.corpuserprofile', verbose_name='Профиль пользователя'),
        ),
        migrations.AlterField(
            model_name='corpuseraccess',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='corpuseraccess',
            name='level',
            field=models.IntegerField(verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='corpuserprofile',
            name='access_right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersapp.corpuseraccess', verbose_name='Права доступа'),
        ),
        migrations.AlterField(
            model_name='corpuserprofile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersapp.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='corpuserprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Личный номер телефона'),
        ),
        migrations.AlterField(
            model_name='corpuserprofile',
            name='phone_corp',
            field=models.CharField(blank=True, max_length=15, verbose_name='Корпоративный номер телефона'),
        ),
        migrations.AlterField(
            model_name='corpuserprofile',
            name='phone_internal',
            field=models.CharField(blank=True, max_length=3, verbose_name='Внутренний номер'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Наименование на английском'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersapp.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
