# Generated by Django 3.2.5 on 2021-07-21 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersapp', '0004_auto_20210721_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название типа документа')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('number', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Номер документа')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название документа')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата создания документа')),
                ('document', models.FileField(blank=True, upload_to='media', verbose_name='Документ')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор документа')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersapp.department', verbose_name='Подразделение')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentapp.doctype', verbose_name='Тип документа')),
            ],
        ),
    ]
